PCWEB-10138 Flex 컴포넌트의 gap/width/height 타입으로 number를 허용한다
dramancompany/rui pull request #39
Opened 2023-03-31 07:54 UTC by JeongminSung

## 작업 내용 (Content) 📝

- 기존의 string만 받을 수 있던 width, height, gap 속성을 number 타입도 받을 수 있도록 변경되었으며, 하위 호환성 문제를 방지하기 위해 string 타입일 경우 그대로 적용되도록 구현되었습니다.
- `<Flex gap="10px" width="40px" height="60px" />`  ✅
- `<Flex gap={10} width={40} height={60} />` ✅
## 스크린샷 (Screenshot) 📷

- 필요하다면 스크린샷을 첨부해주세요.
- Attach a Screenshot if necessary.

## 링크 (Links) 🔗

- [PCWEB-10138](https://dramancompany.atlassian.net/browse/PCWEB-10138)

## 기타 사항 (Etc) 🔖

- PR에 대한 추가 설명이나 작업하면서 고민이 되었던 부분 등
- Additional information about this PR or any troubles working on this PR.
- Merge 전 필요한 작업이 있다면 적어주세요 (Checklist before merge)
- [ ] eg) Create XX table, Deploy app etc

## 테스트 Checklist (Test Checklist) ✅

- 꼭 테스트 해봐야하는 시나리오를 적어주세요
- [ ] eg) Test case

## 희망 리뷰 완료 일 (Expected due date) ⏰

`202X.X.X. Wed`

2023-03-31 07:55 UTC, kimjeongwonn requested changes
오타가 있어요!!

2023-03-31 07:55 UTC, kimjeongwonn commented on src/components/Common/Flex/Flex.tsx
> +  height: ${({ width = 'auto' }) =>
```suggestion
  width: ${({ width = 'auto' }) =>
```

2023-03-31 07:57 UTC, JeongminSung commented on src/components/Common/Flex/Flex.tsx
> +  height: ${({ width = 'auto' }) =>
수정 완료!

2023-03-31 07:58 UTC, kimjeongwonn approved these changes
고생하셨슴다!

2023-03-31 08:08 UTC, kimjeongwonn commented on src/components/Common/Flex/Flex.tsx
> +  height: ${({ width = 'auto' }) =>
엇 생각해보니 이것도 수정이 필요할 것 같긴 하군요...

2023-04-04 01:14 UTC, saengmotmi commented
@JeongminSung 콘솔 지워주십씨오!

2023-04-06 02:49 UTC, kimjeongwonn commented
요거 제가 리뷰한내용 포함해서 정리한 뒤 merge할게용~

2023-04-06 04:53 UTC, kimjeongwonn commented
> @JeongminSung 린트 해결해주세요! Object.assign() 사용하시면 될거 같습니다

@saengmotmi  function에 name을 넣는 방법이나, 화살표 함수로 만들어서 익명함수를 할당해도 해결될 것 같은데
assign으로 속성할당을 권유하신건지 따로 이유가 있다면 알 수 있을까요?! assign으로하게되면 자동 타이핑이 누락되어서 별도로 타입을 지정해야 할 것 같아서요!!

2023-04-06 04:54 UTC, saengmotmi commented
@kimjeongwonn 오 아니요 그런 이슈가 있는지 몰랐어서 말씀해주신 방법으로 하는게 좋을거 같습니다

2023-04-06 05:03 UTC, merged