RUI-20 typography 수정
dramancompany/rui pull request #50
Opened 2023-08-08 08:55 UTC by kimjeongwonn

## 작업 내용 (Content) 📝

- Typography명 변경
  - 기존 Typography명은 그대로 유지 (legacy로 관리해야함)
- Typography 컴포넌트 수정
  - variant props 필수
    - `variant`를 비울거면 사용하는 의미가 없는 컴포넌트 상식적인 기본값이 없는상황에 기본값을 넣으면 더 혼란스러워질 것으로 예상
  - tagName을 제한하지 않음
    - styled-components의 as와 동일한 사용성
  - ref전달
    - 단 as를 통해서 어떤 컴포넌트가 들어올 지 모르기 때문에 HTMLElement타입으로 지정, callbackRef등을 사용할 경우 필요에 따라 `instanceof`로 타입을 좁혀 사용해야 합니다.

## 스크린샷 (Screenshot) 📷

## 링크 (Links) 🔗

- [JIRA 티켓 이름](https://dramancompany.atlassian.net/browse/RUI-20)

## 기타 사항 (Etc) 🔖

- PR에 대한 추가 설명이나 작업하면서 고민이 되었던 부분 등
- Additional information about this PR or any troubles working on this PR.
- Merge 전 필요한 작업이 있다면 적어주세요 (Checklist before merge)
- [ ] eg) Create XX table, Deploy app etc

## 테스트 Checklist (Test Checklist) ✅

- 꼭 테스트 해봐야하는 시나리오를 적어주세요
- [ ] eg) Test case

## 희망 리뷰 완료 일 (Expected due date) ⏰

`202X.X.X. Wed`

2023-08-08 09:55 UTC, saengmotmi commented
fyi) https://kciter.so/posts/polymorphic-react-component 컴포넌트 다형성에 대한 아티클입니다

2023-08-09 08:05 UTC, saengmotmi requested changes
구두로 의견드린 내용을 간략하게 정리하겠습니다
- Typography의 prop을 제약하지 않고 html 태그를 다형적으로 지원할 수 있도록 타이핑을 강화하면 좋겠음
- Body1_M을 variant의 기본 값으로 사용할 수 있을지 확인 필요

2023-08-17 01:13 UTC, yongsk0066 approved these changes

2023-08-17 01:13 UTC, yongsk0066 commented on src/components/Common/Typography/index.tsx
> +    as={as as never}
KnownTarget 타입을 쓰면 될것같은데 v5에는 없는거같군요.. as never 는 빼도 되지 않을까요?

2023-08-17 01:18 UTC, kimjeongwonn commented on src/components/Common/Typography/index.tsx
> +    as={as as never}
요 형태에서는 ref의 타입추론이 styled-component에서 예측하는대로 되지 않는 상황이라서 (T제네릭에 따라 달라지기 때문에) styled-components에서는 as타입을 막아버립니다 (never타입으로 지정됨) 그런데 wrapping하고 있는 Typography 컴포넌트에서는 다형성을 지원하고 컴포넌트가 이미 들어올 타입을 알고있어서 (T의 제네릭을 ElementType으로 좁혀놨기 때문에) as동작에 대한 보장이 된 상태라서 어쩔 수 없이 never로 assertion했습니다...ㅠㅠ

2023-08-18 00:20 UTC, JeongminSung approved these changes
수고하셨습니다!

2023-08-21 07:53 UTC, kimjeongwonn commented
@saengmotmi 요거 merge해볼까 하는데 다형성 처리한 것 확인 해주시고 approve 해주시면 감사하겠습니다!

2023-08-21 07:56 UTC, saengmotmi approved these changes
수고하셨습니다!

2023-08-21 08:03 UTC, merged